In [1]:
from cupy import ndarray
from typing import List, Any, Tuple

import cupy
import mytensor as t
import sys

In [2]:
def t_update(t):
  pending_for_deletion = []
  for i in sys.modules:
    if i.split('.')[0] == 'mytensor':
      pending_for_deletion.append(i)

  for i in pending_for_deletion:
    del sys.modules[i]

  import mytensor as t
  return t

In [3]:
x = cupy.random.normal(size=(100, 7))
y = cupy.random.normal(size=(100, 1))
W0 = cupy.random.normal(size=(7, 5))
W1 = cupy.random.normal(size=(5, 1))

x = t.TensorNode(x, name='x')
y = t.TensorNode(y, name='y')
W0 = t.TensorNode(W0, name='W0', is_weight=True)
W1 = t.TensorNode(W1, name='W1', is_weight=True)

In [4]:
y0 = x@W0
y1 = y0@W1
delta = y1 - y
squared = delta**2.
L = squared.reduce_sum(0) / 2.

In [5]:
import copy

In [6]:
t = t_update(t)
a = t.TensorNode(cupy.random.normal(size=(100,100)), name='a')
b = t.TensorNode(cupy.random.normal(size=(100,50)), name='b')
c = t.TensorNode(cupy.random.normal(size=(50,2)), name='c')

z = a@b
r = z@c
copy_r = copy.deepcopy(r)
d = r/2.
dd = d + copy_r
e = dd.reduce_sum(0)
u = e.reduce_sum(1)
f = u/3.
h = f/10.

In [8]:
u.propagate()

AttributeError: 'NoneType' object has no attribute 'updated'

In [ ]:
r = cupy.ones((10,1))
cupy.repeat(r, 3, axis=1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x.tensor**4.0
import operator
operator.pow(x.tensor, 4.0)

array([34588537.41247571])

In [ ]:
y = cupy.array([1,2,3,4,5], dtype=cupy.float32)
y**y

array([1.000e+00, 4.000e+00, 2.700e+01, 2.560e+02, 3.125e+03],
      dtype=float32)

In [ ]:
def a(**kwargs):
  print(kwargs)
  for i in kwargs:
    print(i)

In [ ]:
a(s=12,g=13)

{'s': 12, 'g': 13}
s
g


In [ ]:
def bb(der, pax):
  print(der)
  print(pax)
  pass

In [ ]:
zy = {'pax': 11, 'der': 12, 'sropt':2}
bb(**zy)

TypeError: bb() got an unexpected keyword argument 'sropt'

In [ ]:
grad_computer = t.GradComputer()
grad_computer.decide_and_calc_gradient(g)

secondary


In [ ]:
a = cupy.array([1,2,3,4,5], dtype=cupy.float32)

kernel = '''
  float eps = 1E-6;
  float incremented = x + eps;
  float delta_numerator = 
'''
r = cupy.ElementwiseKernel('float32 x, float32 y', 'float32 z', kernel)

In [ ]:
r(a, a)

array([3.3, 4.3, 5.3, 6.3, 7.3], dtype=float32)

In [ ]:
x = t.TensorNode([[12,3],[5,6]], name='x')
y = t.TensorNode([[10,5],[1,7]], name='y')

z = x@y

r = z/a

TensorNodeError: Foreign type tensor.

In [ ]:
x = t.TensorNode(cupy.random.normal(size=(1000,1000)))
y = t.TensorNode(cupy.random.normal(size=(1000,7000)))

z = x@y

In [ ]:
z

TensorNode
Name:(None@None)
Memory:139809093233552
[[ 37.29762068   4.53384792  30.61500471 ...  60.18328411 -18.90310318
  -64.15940643]
 [ 37.58950326  -0.57364144  19.85995657 ... -12.2005313  -34.91459
  -23.57267975]
 [ 44.97245058  -2.88021537 -23.27193722 ...  37.02139232   0.76180238
   12.53589196]
 ...
 [ 27.95091232  48.54498078  35.48940676 ...  -9.87125267  26.09058185
    3.66317272]
 [ 23.12697985  15.0095266   12.72206292 ... -10.68657581  84.56579232
    9.6026919 ]
 [-19.06869712  38.79325013  92.84293647 ...  -4.75683846  14.98012206
   -4.32979292]]

In [ ]:
z.T

array([[ 19.28495069, -51.43219486, -49.93712694, ..., -30.26086317,
         -9.22155791,  -3.55087861],
       [ 29.44045447, -14.40859038,  -3.86330677, ...,  10.3874261 ,
         -1.20654702, -24.54852436],
       [  1.80022564,  46.27791937, -24.09992972, ...,   4.95694029,
        -19.17808276,  18.45007159],
       ...,
       [ 10.58481411,  17.0488717 ,  10.1886063 , ...,   3.79476739,
        -23.67104739, -43.76786755],
       [ 19.24795907,  -4.75976313,  45.22347638, ...,  -6.54302496,
        -15.54353629,  97.59695314],
       [ -9.75638605,   3.98154961,  21.63385428, ..., -25.23079375,
         10.2798262 ,   0.27620558]])

In [ ]:
z.T()

In [ ]:
import operator

In [ ]:
operator.add(1,3)

4